"""empty message

Revision ID: 5e5f2cb59ac7
Revises: 
Create Date: 2021-09-16 20:43:24.095151

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5e5f2cb59ac7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hearts', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('high_score', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('rank', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=80), nullable=True))
    op.alter_column('user', 'email',
                    existing_type=sa.VARCHAR(length=80),
                    )
    op.alter_column('user', 'password_hash',
                    existing_type=sa.VARCHAR(length=50),
                    )
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'name')
    op.drop_column('user', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('score', sa.INTEGER(), nullable=False))
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=80), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'password_hash',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=False)
    op.alter_column('user', 'email',
                    existing_type=sa.VARCHAR(length=80),
                    nullable=False)
    op.drop_column('user', 'username')
    op.drop_column('user', 'rank')
    op.drop_column('user', 'high_score')
    op.drop_column('user', 'hearts')
    # ### end Alembic commands ###
